// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.github.os72.protobuf241.ExtensionRegistry registry) {
  }
  public interface HelloRequestOrBuilder
      extends com.github.os72.protobuf241.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class HelloRequest extends
      com.github.os72.protobuf241.GeneratedMessage
      implements HelloRequestOrBuilder {
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(Builder builder) {
      super(builder);
    }
    private HelloRequest(boolean noInit) {}
    
    private static final HelloRequest defaultInstance;
    public static HelloRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public HelloRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.github.os72.protobuf241.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorld.internal_static_HelloRequest_descriptor;
    }
    
    protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorld.internal_static_HelloRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.github.os72.protobuf241.ByteString bs = 
            (com.github.os72.protobuf241.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.github.os72.protobuf241.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.github.os72.protobuf241.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.github.os72.protobuf241.ByteString b = 
            com.github.os72.protobuf241.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf241.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.github.os72.protobuf241.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HelloWorld.HelloRequest parseFrom(
        com.github.os72.protobuf241.ByteString data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(
        com.github.os72.protobuf241.ByteString data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(byte[] data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(
        byte[] data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HelloWorld.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HelloWorld.HelloRequest parseFrom(
        com.github.os72.protobuf241.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HelloWorld.HelloRequest parseFrom(
        com.github.os72.protobuf241.CodedInputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HelloWorld.HelloRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf241.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.github.os72.protobuf241.GeneratedMessage.Builder<Builder>
       implements HelloWorld.HelloRequestOrBuilder {
      public static final com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptor() {
        return HelloWorld.internal_static_HelloRequest_descriptor;
      }
      
      protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloWorld.internal_static_HelloRequest_fieldAccessorTable;
      }
      
      // Construct using HelloWorld.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf241.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloWorld.HelloRequest.getDescriptor();
      }
      
      public HelloWorld.HelloRequest getDefaultInstanceForType() {
        return HelloWorld.HelloRequest.getDefaultInstance();
      }
      
      public HelloWorld.HelloRequest build() {
        HelloWorld.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HelloWorld.HelloRequest buildParsed()
          throws com.github.os72.protobuf241.InvalidProtocolBufferException {
        HelloWorld.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HelloWorld.HelloRequest buildPartial() {
        HelloWorld.HelloRequest result = new HelloWorld.HelloRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.github.os72.protobuf241.Message other) {
        if (other instanceof HelloWorld.HelloRequest) {
          return mergeFrom((HelloWorld.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HelloWorld.HelloRequest other) {
        if (other == HelloWorld.HelloRequest.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.github.os72.protobuf241.CodedInputStream input,
          com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.os72.protobuf241.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf241.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.github.os72.protobuf241.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.github.os72.protobuf241.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:HelloRequest)
    }
    
    static {
      defaultInstance = new HelloRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HelloRequest)
  }
  
  public interface HelloReplyOrBuilder
      extends com.github.os72.protobuf241.MessageOrBuilder {
    
    // required string message = 1;
    boolean hasMessage();
    String getMessage();
  }
  public static final class HelloReply extends
      com.github.os72.protobuf241.GeneratedMessage
      implements HelloReplyOrBuilder {
    // Use HelloReply.newBuilder() to construct.
    private HelloReply(Builder builder) {
      super(builder);
    }
    private HelloReply(boolean noInit) {}
    
    private static final HelloReply defaultInstance;
    public static HelloReply getDefaultInstance() {
      return defaultInstance;
    }
    
    public HelloReply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.github.os72.protobuf241.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorld.internal_static_HelloReply_descriptor;
    }
    
    protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorld.internal_static_HelloReply_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.github.os72.protobuf241.ByteString bs = 
            (com.github.os72.protobuf241.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.github.os72.protobuf241.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.github.os72.protobuf241.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.github.os72.protobuf241.ByteString b = 
            com.github.os72.protobuf241.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf241.ByteString) ref;
      }
    }
    
    private void initFields() {
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.github.os72.protobuf241.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static HelloWorld.HelloReply parseFrom(
        com.github.os72.protobuf241.ByteString data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(
        com.github.os72.protobuf241.ByteString data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(byte[] data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(
        byte[] data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static HelloWorld.HelloReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HelloWorld.HelloReply parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static HelloWorld.HelloReply parseFrom(
        com.github.os72.protobuf241.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static HelloWorld.HelloReply parseFrom(
        com.github.os72.protobuf241.CodedInputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HelloWorld.HelloReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf241.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.github.os72.protobuf241.GeneratedMessage.Builder<Builder>
       implements HelloWorld.HelloReplyOrBuilder {
      public static final com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptor() {
        return HelloWorld.internal_static_HelloReply_descriptor;
      }
      
      protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloWorld.internal_static_HelloReply_fieldAccessorTable;
      }
      
      // Construct using HelloWorld.HelloReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf241.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloWorld.HelloReply.getDescriptor();
      }
      
      public HelloWorld.HelloReply getDefaultInstanceForType() {
        return HelloWorld.HelloReply.getDefaultInstance();
      }
      
      public HelloWorld.HelloReply build() {
        HelloWorld.HelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private HelloWorld.HelloReply buildParsed()
          throws com.github.os72.protobuf241.InvalidProtocolBufferException {
        HelloWorld.HelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public HelloWorld.HelloReply buildPartial() {
        HelloWorld.HelloReply result = new HelloWorld.HelloReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.github.os72.protobuf241.Message other) {
        if (other instanceof HelloWorld.HelloReply) {
          return mergeFrom((HelloWorld.HelloReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(HelloWorld.HelloReply other) {
        if (other == HelloWorld.HelloReply.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.github.os72.protobuf241.CodedInputStream input,
          com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.os72.protobuf241.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf241.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string message = 1;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.github.os72.protobuf241.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.github.os72.protobuf241.ByteString value) {
        bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:HelloReply)
    }
    
    static {
      defaultInstance = new HelloReply(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HelloReply)
  }
  
  private static com.github.os72.protobuf241.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  private static
    com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  private static com.github.os72.protobuf241.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  private static
    com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;
  
  public static com.github.os72.protobuf241.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.github.os72.protobuf241.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HelloWorld.proto\"\034\n\014HelloRequest\022\014\n\004na" +
      "me\030\001 \002(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \002(\t2" +
      "1\n\007Greeter\022&\n\010SayHello\022\r.HelloRequest\032\013." +
      "HelloReply"
    };
    com.github.os72.protobuf241.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.github.os72.protobuf241.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.github.os72.protobuf241.ExtensionRegistry assignDescriptors(
            com.github.os72.protobuf241.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HelloRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HelloRequest_fieldAccessorTable = new
            com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable(
              internal_static_HelloRequest_descriptor,
              new java.lang.String[] { "Name", },
              HelloWorld.HelloRequest.class,
              HelloWorld.HelloRequest.Builder.class);
          internal_static_HelloReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HelloReply_fieldAccessorTable = new
            com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable(
              internal_static_HelloReply_descriptor,
              new java.lang.String[] { "Message", },
              HelloWorld.HelloReply.class,
              HelloWorld.HelloReply.Builder.class);
          return null;
        }
      };
    com.github.os72.protobuf241.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.github.os72.protobuf241.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
